In [52]:
import pandas as pd
import numpy as np

In [55]:
data=pd.read_csv("Tugas2.csv",sep=",")

In [56]:
data.head()

Unit_1  Unit_2  Unit_3  Unit_4  Unit_5  Unit_6  Unit_7  Unit_8  Unit_9  \
0  14.830  14.166  14.730     0.0  15.229  15.121    14.1     0.0  14.309   
1  14.237  14.154  13.943     0.0  13.682  14.549    14.4     0.0  15.012   
2  14.284  14.803  14.605     0.0  15.132  14.139    14.4     0.0  14.292   
3  14.927  14.289  13.953     0.0  14.683  14.935    14.1     0.0  13.655   
4  14.772  13.916  13.919     0.0  14.417  14.091    14.8     0.0  14.493   

   Unit_10  Unit_11      Date  
0   14.313      0.0  1-Jan-18  
1   14.646      0.0  1-Jan-18  
2   14.665      0.0  1-Jan-18  
3   14.705      0.0  1-Jan-18  
4   15.787      0.0  1-Jan-18

In [57]:
data.describe()

Unit_1       Unit_2       Unit_3       Unit_4       Unit_5  \
count  8722.000000  8722.000000  8722.000000  8722.000000  8722.000000   
mean      9.105875     7.566096     7.003712     8.052582     7.697368   
std       7.188641     7.423728     7.355037     7.276336     7.376626   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%      13.375000    11.376000     0.000000    11.990000    11.800000   
75%      15.200000    14.900000    14.560000    14.882250    15.041500   
max      16.830000    16.940000    16.910000    16.930000    16.920000   

            Unit_6       Unit_7       Unit_8       Unit_9      Unit_10  \
count  8722.000000  8722.000000  8722.000000  8722.000000  8722.000000   
mean      7.952345     5.160551     4.526493     4.950944     5.562605   
std       7.115470     6.951884     6.798168     6.967225     7.228889   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%      12.001500     0.000000     0.000000     0.000000     0.000000   
75%      14.554500    13.712250    12.360000    13.674500    14.419250   
max      16.920000    16.930000    16.910000    17.080000    17.000000   

           Unit_11  
count  8722.000000  
mean      5.557211  
std       7.218234  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%      14.300000  
max      16.940000

In [58]:
import numpy as np
np.sum(data.isnull())

Unit_1     147
Unit_2     147
Unit_3     147
Unit_4     147
Unit_5     147
Unit_6     147
Unit_7     147
Unit_8     147
Unit_9     147
Unit_10    147
Unit_11    147
Date         0
dtype: int64

In [59]:
data['Unit_1']=data['Unit_1'].fillna((data['Unit_1'].median()))
data['Unit_2']=data['Unit_2'].fillna((data['Unit_2'].median()))
data['Unit_3']=data['Unit_3'].fillna((data['Unit_3'].median()))
data['Unit_4']=data['Unit_4'].fillna((data['Unit_4'].median()))
data['Unit_5']=data['Unit_5'].fillna((data['Unit_5'].median()))
data['Unit_6']=data['Unit_6'].fillna((data['Unit_6'].median()))
data['Unit_7']=data['Unit_7'].fillna((data['Unit_7'].median()))
data['Unit_8']=data['Unit_8'].fillna((data['Unit_8'].median()))
data['Unit_9']=data['Unit_9'].fillna((data['Unit_9'].median()))
data['Unit_10']=data['Unit_10'].fillna((data['Unit_10'].median()))
data['Unit_11']=data['Unit_11'].fillna((data['Unit_11'].median()))
np.sum(data.isnull())

Unit_1     0
Unit_2     0
Unit_3     0
Unit_4     0
Unit_5     0
Unit_6     0
Unit_7     0
Unit_8     0
Unit_9     0
Unit_10    0
Unit_11    0
Date       0
dtype: int64

In [60]:
from scipy import stats
z = np.abs(stats.zscore(data._get_numeric_data()))
print(z)
data=data[(z<3).all(axis=1)]
print(data.shape)

[[0.79076728 0.88603006 1.067277   ... 1.3606976  1.22755583 0.75979855]
 [0.70782111 0.88440351 0.9601733  ... 1.46202796 1.27378391 0.75979855]
 [0.71439526 0.97237275 1.05026561 ... 1.35824722 1.27642155 0.75979855]
 ...
 [1.2835862  1.034112   0.93734496 ... 0.70180051 0.75941868 0.95857902]
 [1.2835862  1.034112   0.93734496 ... 0.70180051 0.75941868 1.03504404]
 [1.2835862  1.034112   0.93734496 ... 0.70180051 0.75941868 1.02114131]]
(8869, 12)
