# Latihan 4

In [33]:
import pandas as pd
import numpy as np

In [34]:
data=pd.read_csv('Latihan4.csv')
data.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am      ...      Humidity3pm  \
0           W           44.0          W      ...             22.0   
1         WNW           44.0        NNW      ...             25.0   
2         WSW           46.0          W      ...             30.0   
3          NE           24.0         SE      ...             16.0   
4           W           41.0        ENE      ...             33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RISK_MM  RainTomorrow  
0      0.0            No  
1      0.0            No  
2      0.0            No  
3      1.0            No  
4      0.2            No  

[5 rows x 24 columns]

In [35]:
data.describe()

MinTemp        MaxTemp       Rainfall   Evaporation  \
count  143975.000000  144199.000000  142199.000000  82670.000000   
mean       12.194034      23.221348       2.360918      5.468232   
std         6.398495       7.119049       8.478060      4.193704   
min        -8.500000      -4.800000       0.000000      0.000000   
25%         7.600000      17.900000       0.000000      2.600000   
50%        12.000000      22.600000       0.000000      4.800000   
75%        16.900000      28.200000       0.800000      7.400000   
max        33.900000      48.100000     371.000000    145.000000   

           Sunshine  WindGustSpeed   WindSpeed9am   WindSpeed3pm  \
count  75625.000000  135197.000000  143693.000000  142398.000000   
mean       7.611178      40.035230      14.043426      18.662657   
std        3.785483      13.607062       8.915375       8.809800   
min        0.000000       6.000000       0.000000       0.000000   
25%        4.800000      31.000000       7.000000      13.000000   
50%        8.400000      39.000000      13.000000      19.000000   
75%       10.600000      48.000000      19.000000      24.000000   
max       14.500000     135.000000     130.000000      87.000000   

         Humidity9am    Humidity3pm   Pressure9am    Pressure3pm  \
count  142806.000000  140953.000000  130395.00000  130432.000000   
mean       68.880831      51.539116    1017.64994    1015.255889   
std        19.029164      20.795902       7.10653       7.037414   
min         0.000000       0.000000     980.50000     977.100000   
25%        57.000000      37.000000    1012.90000    1010.400000   
50%        70.000000      52.000000    1017.60000    1015.200000   
75%        83.000000      66.000000    1022.40000    1020.000000   
max       100.000000     100.000000    1041.00000    1039.600000   

           Cloud9am      Cloud3pm        Temp9am       Temp3pm        RISK_MM  
count  89572.000000  86102.000000  143693.000000  141851.00000  142193.000000  
mean       4.447461      4.509930      16.990631      21.68339       2.360682  
std        2.887159      2.720357       6.488753       6.93665       8.477969  
min        0.000000      0.000000      -7.200000      -5.40000       0.000000  
25%        1.000000      2.000000      12.300000      16.60000       0.000000  
50%        5.000000      5.000000      16.700000      21.10000       0.000000  
75%        7.000000      7.000000      21.600000      26.40000       0.800000  
max        9.000000      9.000000      40.200000      46.70000     371.000000

In [36]:
np.sum(data.isnull())

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RISK_MM           3267
RainTomorrow      3267
dtype: int64

In [37]:
data['MinTemp']=data['MinTemp'].fillna((data['MinTemp'].median()))
data['MaxTemp']=data['MaxTemp'].fillna((data['MaxTemp'].median()))
data['Rainfall']=data['Rainfall'].fillna((data['Rainfall'].median()))
data['Evaporation']=data['Evaporation'].fillna((data['Evaporation'].median()))
data['Sunshine']=data['Sunshine'].fillna((data['Sunshine'].median()))
data['WindGustSpeed']=data['WindGustSpeed'].fillna((data['WindGustSpeed'].median()))
data['WindSpeed9am']=data['WindSpeed9am'].fillna((data['WindSpeed9am'].median()))
data['WindSpeed3pm']=data['WindSpeed3pm'].fillna((data['WindSpeed3pm'].median()))
data['Humidity9am']=data['Humidity9am'].fillna((data['Humidity9am'].median()))
data['Humidity3pm']=data['Humidity3pm'].fillna((data['Humidity3pm'].median()))
data['Pressure9am']=data['Pressure9am'].fillna((data['Pressure9am'].median()))
data['Pressure3pm']=data['Pressure3pm'].fillna((data['Pressure3pm'].median()))
data['Cloud9am']=data['Cloud9am'].fillna((data['Cloud9am'].median()))
data['Cloud3pm']=data['Cloud3pm'].fillna((data['Cloud3pm'].median()))
data['Temp9am']=data['Temp9am'].fillna((data['Temp9am'].median()))
data['Temp3pm']=data['Temp3pm'].fillna((data['Temp3pm'].median()))
data['RISK_MM']=data['RISK_MM'].fillna((data['RISK_MM'].median()))
np.sum(data.isnull())

Date                 0
Location             0
MinTemp              0
MaxTemp              0
Rainfall             0
Evaporation          0
Sunshine             0
WindGustDir      10326
WindGustSpeed        0
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am         0
WindSpeed3pm         0
Humidity9am          0
Humidity3pm          0
Pressure9am          0
Pressure3pm          0
Cloud9am             0
Cloud3pm             0
Temp9am              0
Temp3pm              0
RainToday         3261
RISK_MM              0
RainTomorrow      3267
dtype: int64

In [38]:
data['WindGustDir']=data['WindGustDir'].fillna(data['WindGustDir']).dropna().mode()[0]
data['WindDir9am']=data['WindDir9am'].fillna(data['WindDir9am']).dropna().mode()[0]
data['WindDir3pm']=data['WindDir3pm'].fillna(data['WindDir3pm']).dropna().mode()[0]
data['RainToday']=data['RainToday'].fillna(data['RainToday']).dropna().mode()[0]
data['RainTomorrow']=data['RainTomorrow'].fillna(data['RainTomorrow']).dropna().mode()[0]
data.isnull().sum()

Date             0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RISK_MM          0
RainTomorrow     0
dtype: int64

In [39]:
#mengatasi outlier
from scipy import stats
z=np.abs(stats.zscore(data._get_numeric_data()))
print(z)
data1=data[(z<3).all(axis=1)]
data1.head()
print(data1.shape)

[[0.18975691 0.0445749  0.20358073 ... 0.01350553 0.0191346  0.27506582]
 [0.75278601 0.26579424 0.27509664 ... 0.03301131 0.3840643  0.27506582]
 [0.11121166 0.35044037 0.27509664 ... 0.62222462 0.22349523 0.27506582]
 ...
 [1.06696699 0.51973264 0.27509664 ... 0.69575252 0.64681369 0.27506582]
 [0.68994982 0.53384032 0.27509664 ... 0.29260657 0.6322165  0.27506582]
 [0.42539264 0.08689797 0.27509664 ... 0.30811219 0.11224009 0.27506582]]
(134646, 24)


In [40]:
data1

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       2008-12-01   Albury     13.4     22.9       0.6          4.8   
1       2008-12-02   Albury      7.4     25.1       0.0          4.8   
2       2008-12-03   Albury     12.9     25.7       0.0          4.8   
3       2008-12-04   Albury      9.2     28.0       0.0          4.8   
4       2008-12-05   Albury     17.5     32.3       1.0          4.8   
5       2008-12-06   Albury     14.6     29.7       0.2          4.8   
6       2008-12-07   Albury     14.3     25.0       0.0          4.8   
7       2008-12-08   Albury      7.7     26.7       0.0          4.8   
9       2008-12-10   Albury     13.1     30.1       1.4          4.8   
10      2008-12-11   Albury     13.4     30.4       0.0          4.8   
11      2008-12-12   Albury     15.9     21.7       2.2          4.8   
13      2008-12-14   Albury     12.6     21.0       3.6          4.8   
14      2008-12-15   Albury      8.4     24.6       0.0          4.8   
15      2008-12-16   Albury      9.8     27.7       0.0          4.8   
16      2008-12-17   Albury     14.1     20.9       0.0          4.8   
17      2008-12-18   Albury     13.5     22.9      16.8          4.8   
18      2008-12-19   Albury     11.2     22.5      10.6          4.8   
19      2008-12-20   Albury      9.8     25.6       0.0          4.8   
20      2008-12-21   Albury     11.5     29.3       0.0          4.8   
21      2008-12-22   Albury     17.1     33.0       0.0          4.8   
22      2008-12-23   Albury     20.5     31.8       0.0          4.8   
23      2008-12-24   Albury     15.3     30.9       0.0          4.8   
24      2008-12-25   Albury     12.6     32.4       0.0          4.8   
25      2008-12-26   Albury     16.2     33.9       0.0          4.8   
26      2008-12-27   Albury     16.9     33.0       0.0          4.8   
27      2008-12-28   Albury     20.1     32.7       0.0          4.8   
28      2008-12-29   Albury     19.7     27.2       0.0          4.8   
29      2008-12-30   Albury     12.5     24.2       1.2          4.8   
30      2008-12-31   Albury     12.0     24.4       0.8          4.8   
31      2009-01-01   Albury     11.3     26.5       0.0          4.8   
...            ...      ...      ...      ...       ...          ...   
145430  2017-05-27    Uluru      9.3     28.0       0.0          4.8   
145431  2017-05-28    Uluru      8.0     24.6       0.0          4.8   
145432  2017-05-29    Uluru     12.7     22.2       0.0          4.8   
145433  2017-05-30    Uluru      9.4     22.7       0.0          4.8   
145434  2017-05-31    Uluru      5.4     20.5       0.0          4.8   
145435  2017-06-01    Uluru      5.6     19.4       0.0          4.8   
145436  2017-06-02    Uluru      1.5     19.2       0.0          4.8   
145437  2017-06-03    Uluru      3.8     19.8       0.0          4.8   
145438  2017-06-04    Uluru      4.5     18.8       0.0          4.8   
145439  2017-06-05    Uluru      4.9     20.7       0.0          4.8   
145440  2017-06-06    Uluru      1.2     20.8       0.0          4.8   
145441  2017-06-07    Uluru      0.5     21.7       0.0          4.8   
145442  2017-06-08    Uluru      4.0     20.0       0.0          4.8   
145443  2017-06-09    Uluru      3.4     19.8       0.0          4.8   
145444  2017-06-10    Uluru      3.2     18.6       0.0          4.8   
145445  2017-06-11    Uluru      2.4     19.1       0.0          4.8   
145446  2017-06-12    Uluru      5.1     19.7       0.0          4.8   
145447  2017-06-13    Uluru      2.5     21.2       0.0          4.8   
145448  2017-06-14    Uluru      2.3     21.4       0.0          4.8   
145449  2017-06-15    Uluru      2.6     22.5       0.0          4.8   
145450  2017-06-16    Uluru      5.2     24.3       0.0          4.8   
145451  2017-06-17    Uluru      6.4     23.4       0.0          4.8   
145452  2017-06-18    Uluru      8.0     20.7       0.0          4.8   
145453  2017-06-19    Uluru      7.4     20.6       0.

In [46]:
#data untuk transformasi
data2=data1.drop(['Date','Location','WindGustDir','WindDir9am','WindDir3pm','RainToday','RainTomorrow'],1)
data2

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustSpeed  \
0          13.4     22.9       0.6          4.8       8.4           44.0   
1           7.4     25.1       0.0          4.8       8.4           44.0   
2          12.9     25.7       0.0          4.8       8.4           46.0   
3           9.2     28.0       0.0          4.8       8.4           24.0   
4          17.5     32.3       1.0          4.8       8.4           41.0   
5          14.6     29.7       0.2          4.8       8.4           56.0   
6          14.3     25.0       0.0          4.8       8.4           50.0   
7           7.7     26.7       0.0          4.8       8.4           35.0   
9          13.1     30.1       1.4          4.8       8.4           28.0   
10         13.4     30.4       0.0          4.8       8.4           30.0   
11         15.9     21.7       2.2          4.8       8.4           31.0   
13         12.6     21.0       3.6          4.8       8.4           44.0   
14          8.4     24.6       0.0          4.8       8.4           39.0   
15          9.8     27.7       0.0          4.8       8.4           50.0   
16         14.1     20.9       0.0          4.8       8.4           22.0   
17         13.5     22.9      16.8          4.8       8.4           63.0   
18         11.2     22.5      10.6          4.8       8.4           43.0   
19          9.8     25.6       0.0          4.8       8.4           26.0   
20         11.5     29.3       0.0          4.8       8.4           24.0   
21         17.1     33.0       0.0          4.8       8.4           43.0   
22         20.5     31.8       0.0          4.8       8.4           41.0   
23         15.3     30.9       0.0          4.8       8.4           33.0   
24         12.6     32.4       0.0          4.8       8.4           43.0   
25         16.2     33.9       0.0          4.8       8.4           35.0   
26         16.9     33.0       0.0          4.8       8.4           57.0   
27         20.1     32.7       0.0          4.8       8.4           48.0   
28         19.7     27.2       0.0          4.8       8.4           46.0   
29         12.5     24.2       1.2          4.8       8.4           50.0   
30         12.0     24.4       0.8          4.8       8.4           39.0   
31         11.3     26.5       0.0          4.8       8.4           56.0   
...         ...      ...       ...          ...       ...            ...   
145430      9.3     28.0       0.0          4.8       8.4           28.0   
145431      8.0     24.6       0.0          4.8       8.4           33.0   
145432     12.7     22.2       0.0          4.8       8.4           37.0   
145433      9.4     22.7       0.0          4.8       8.4           35.0   
145434      5.4     20.5       0.0          4.8       8.4           46.0   
145435      5.6     19.4       0.0          4.8       8.4           43.0   
145436      1.5     19.2       0.0          4.8       8.4           37.0   
145437      3.8     19.8       0.0          4.8       8.4           39.0   
145438      4.5     18.8       0.0          4.8       8.4           31.0   
145439      4.9     20.7       0.0          4.8       8.4           37.0   
145440      1.2     20.8       0.0          4.8       8.4           43.0   
145441      0.5     21.7       0.0          4.8       8.4           43.0   
145442      4.0     20.0       0.0          4.8       8.4           39.0   
145443      3.4     19.8       0.0          4.8       8.4           43.0   
145444      3.2     18.6       0.0          4.8       8.4           46.0   
145445      2.4     19.1       0.0          4.8       8.4           33.0   
145446      5.1     19.7       0.0          4.8       8.4           46.0   
145447      2.5     21.2       0.0          4.8       8.4           35.0   
145448      2.3     21.4       0.0          4.8       8.4           22.0   
145449      2.6     22.5       0.0          4.8       8.4           19.0   
145450      5.2     24.3       0.0          4.8       8.

In [48]:
xx = data2.iloc[0:134646,0:17]
xx.head()

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustSpeed  \
0     13.4     22.9       0.6          4.8       8.4           44.0   
1      7.4     25.1       0.0          4.8       8.4           44.0   
2     12.9     25.7       0.0          4.8       8.4           46.0   
3      9.2     28.0       0.0          4.8       8.4           24.0   
4     17.5     32.3       1.0          4.8       8.4           41.0   

   WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  \
0          20.0          24.0         71.0         22.0       1007.7   
1           4.0          22.0         44.0         25.0       1010.6   
2          19.0          26.0         38.0         30.0       1007.6   
3          11.0           9.0         45.0         16.0       1017.6   
4           7.0          20.0         82.0         33.0       1010.8   

   Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RISK_MM  
0       1007.1       8.0       5.0     16.9     21.8      0.0  
1       1007.8       5.0       5.0     17.2     24.3      0.0  
2       1008.7       5.0       2.0     21.0     23.2      0.0  
3       1012.8       5.0       5.0     18.1     26.5      1.0  
4       1006.0       7.0       8.0     17.8     29.7      0.2

In [51]:
#normalization
from sklearn.preprocessing import normalize
xnorm=normalize(xx,norm='l2') #default norm L2, other are L1 and max
xnorm=pd.DataFrame(xnorm) #biar bentuknya tabel
xnorm.tail()

0         1    2         3         4         5         6   \
134641  0.001934  0.016161  0.0  0.003315  0.005801  0.021410  0.008978   
134642  0.002489  0.017492  0.0  0.003319  0.005808  0.015211  0.008988   
134643  0.003742  0.018638  0.0  0.003326  0.005820  0.025637  0.006236   
134644  0.005410  0.018728  0.0  0.003329  0.005827  0.019422  0.009017   
134645  0.010317  0.015649  0.0  0.003324  0.005816  0.027004  0.011771   

              7         8         9         10        11        12        13  \
134641  0.007597  0.035222  0.016575  0.707623  0.704653  0.003453  0.003453   
134642  0.006223  0.038718  0.014519  0.707641  0.704599  0.003457  0.003457   
134643  0.006236  0.036723  0.016629  0.707431  0.704521  0.003464  0.003464   
134644  0.004855  0.035376  0.016647  0.707094  0.705082  0.002081  0.001387   
134645  0.011771  0.042930  0.024927  0.706400  0.704807  0.005539  0.005539   

              14        15   16  
134641  0.006975  0.015470  0.0  
134642  0.007536  0.016939  0.0  
134643  0.008661  0.018084  0.0  
134644  0.010474  0.018035  0.0  
134645  0.010386  0.014471  0.0

In [55]:
#minmax
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(-5,1)) #bebas nilainya yang diinginkan
scaler.fit(xx)
x_scaled= scaler.transform(xx)
x_scaled=pd.DataFrame(x_scaled)
x_scaled.tail()

0         1    2         3         4         5         6   \
134641 -3.464380 -1.971698 -5.0 -3.040816 -1.524138 -2.916667 -3.000000   
134642 -3.337731 -1.702830 -5.0 -3.040816 -1.524138 -3.666667 -3.000000   
134643 -3.052770 -1.476415 -5.0 -3.040816 -1.524138 -2.416667 -3.615385   
134644 -2.672823 -1.462264 -5.0 -3.040816 -1.524138 -3.166667 -3.000000   
134645 -1.548813 -2.084906 -5.0 -3.040816 -1.524138 -2.250000 -2.384615   

              7         8         9         10        11        12        13  \
134641 -3.500000 -2.379310 -3.606061 -0.965261 -1.240602 -1.666667 -1.666667   
134642 -3.772727 -2.034483 -3.787879 -1.129032 -1.421053 -1.666667 -1.666667   
134643 -3.772727 -2.241379 -3.606061 -1.501241 -1.766917 -1.666667 -1.666667   
134644 -4.045455 -2.379310 -3.606061 -1.739454 -1.812030 -3.000000 -3.666667   
134645 -2.681818 -1.620690 -2.878788 -1.620347 -1.601504  0.333333  0.333333   

              14        15   16  
134641 -3.072539 -1.897561 -5.0  
134642 -2.948187 -1.590244 -5.0  
134643 -2.699482 -1.356098 -5.0  
134644 -2.295337 -1.370732 -5.0  
134645 -2.310881 -2.117073 -5.0

In [57]:
#3sigmoid
xsigmoidal=(1-2.7181823**(-xnorm))/(1+2.7181823**(-xnorm))
xsigmoidal=pd.DataFrame(xsigmoidal)
xsigmoidal.tail()

0         1    2         3         4         5         6   \
134641  0.000967  0.008080  0.0  0.001657  0.002901  0.010704  0.004489   
134642  0.001244  0.008746  0.0  0.001659  0.002904  0.007605  0.004494   
134643  0.001871  0.009319  0.0  0.001663  0.002910  0.012817  0.003118   
134644  0.002705  0.009363  0.0  0.001665  0.002913  0.009710  0.004508   
134645  0.005158  0.007824  0.0  0.001662  0.002908  0.013501  0.005885   

              7         8         9         10        11        12        13  \
134641  0.003798  0.017609  0.008287  0.339740  0.338426  0.001727  0.001727   
134642  0.003111  0.019356  0.007259  0.339748  0.338402  0.001728  0.001728   
134643  0.003118  0.018359  0.008314  0.339655  0.338367  0.001732  0.001732   
134644  0.002428  0.017685  0.008323  0.339506  0.338616  0.001040  0.000694   
134645  0.005885  0.021461  0.012462  0.339199  0.338494  0.002770  0.002770   

              14        15   16  
134641  0.003488  0.007735  0.0  
134642  0.003768  0.008469  0.0  
134643  0.004330  0.009042  0.0  
134644  0.005237  0.009017  0.0  
134645  0.005193  0.007235  0.0

In [59]:
#decimal scalling
xdecimal=xx/(10**3) #angka 3 adalah bebas
xdecimal=pd.DataFrame(xdecimal)
xdecimal.tail()

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustSpeed  \
145455   0.0028   0.0234       0.0       0.0048    0.0084          0.031   
145456   0.0036   0.0253       0.0       0.0048    0.0084          0.022   
145457   0.0054   0.0269       0.0       0.0048    0.0084          0.037   
145458   0.0078   0.0270       0.0       0.0048    0.0084          0.028   
145459   0.0149   0.0226       0.0       0.0048    0.0084          0.039   

        WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  \
145455         0.013         0.011        0.051        0.024       1.0246   
145456         0.013         0.009        0.056        0.021       1.0235   
145457         0.009         0.009        0.053        0.024       1.0210   
145458         0.013         0.007        0.051        0.024       1.0194   
145459         0.017         0.017        0.062        0.036       1.0202   

        Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RISK_MM  
145455       1.0203     0.005     0.005   0.0101   0.0224      0.0  
145456       1.0191     0.005     0.005   0.0109   0.0245      0.0  
145457       1.0168     0.005     0.005   0.0125   0.0261      0.0  
145458       1.0165     0.003     0.002   0.0151   0.0260      0.0  
145459       1.0179     0.008     0.008   0.0150   0.0209      0.0

In [61]:
#softmax, mengubah nilai dari 0 sampai 1 untuk transformasi
def softmax(xx):
    return np.exp(xx) / np.sum(np.exp(xx), axis=0)
xsoft=softmax(xnorm)
xsoft=pd.DataFrame(xsoft)
print(xsoft)

              0         1         2         3         4         5         6   \
0       0.000007  0.000007  0.000007  0.000007  0.000007  0.000007  0.000007   
1       0.000007  0.000007  0.000007  0.000007  0.000007  0.000007  0.000007   
2       0.000007  0.000007  0.000007  0.000007  0.000007  0.000007  0.000007   
3       0.000007  0.000007  0.000007  0.000007  0.000007  0.000007  0.000007   
4       0.000007  0.000007  0.000007  0.000007  0.000007  0.000007  0.000007   
5       0.000007  0.000007  0.000007  0.000007  0.000007  0.000008  0.000007   
6       0.000007  0.000007  0.000007  0.000007  0.000007  0.000007  0.000007   
7       0.000007  0.000007  0.000007  0.000007  0.000007  0.000007  0.000007   
8       0.000007  0.000007  0.000007  0.000007  0.000007  0.000007  0.000007   
9       0.000007  0.000007  0.000007  0.000007  0.000007  0.000007  0.000007   
10      0.000007  0.000007  0.000007  0.000007  0.000007  0.000007  0.000007   
11      0.000007  0.000007  0.000007  0.

In [62]:
#feature selection (mencari skor tertinggi lebih dulu)
from sklearn.feature_selection import SelectKBest, chi2, f_regression
Xx=xx.iloc[0:134646,0:17]
y=xx.iloc[0:134646,1]
selector=SelectKBest(f_regression,k="all").fit(Xx,y)
X_new=selector.transform(Xx)
scores=selector.scores_
scores

array([1.52873566e+05, 6.96191353e+17, 3.03310531e+03, 4.72598447e+04,
       1.63809904e+04, 1.13973339e+03, 9.16645132e+01, 6.40075692e+02,
       4.15278725e+04, 4.18712747e+04, 1.76437806e+04, 3.06564005e+04,
       7.32130787e+03, 6.86762679e+03, 4.44474690e+05, 2.12918505e+06,
       1.28003406e+03])